### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by carlospolop** [k4m4/dcipher#1]
Hello,
I was trying this library and I am getting this error, could you check it please?

```
dcipher = require('./index.js')
/home/user/Desktop/git/dcipher/index.js:44
async function dcipherHash (hash, type) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at repl:1:11
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
```

Thank you!

**Comment by k4m4** [comment]
Hi there. I am unable to reproduce this. What version of node are you using? It appears that some versions don't support async functions. Thanks!

**Comment by carlospolop** [comment]
You were right, I have updated node and the problem was solved, thank you!
